### ISSUE TITLE
void bc_usb_cdc_start(void);

### ISSUE THREAD

**Issue by czb** [bigclownlabs/bcf-sdk#155]
`void bc_usb_cdc_start(void);` is not used anywhere in the SDK?

https://github.com/bigclownlabs/bcf-sdk/blob/2b167dce4cce0c460cbb8521e8222c298c1e5dae/bcl/inc/bc_usb_cdc.h#L7

**Comment by hubpav** [comment]
Thanks for telling us - it is a legacy orphan! Will be fixed = deleted.

**Comment by hubpav** [comment]
Fixed in 4f2e504de144204171c6d7b907357a13a26baf56
