### ISSUE TITLE
Remove hard-coded channel from kit's firmwares

### ISSUE THREAD

**Issue by synaptiko** [bigclownlabs/bcf-sdk#161]
I found it strange that I have to define pub channels in kit's firmware like this: https://github.com/bigclownlabs/bcf-kit-wireless-climate-monitor/blob/master/app/application.c#L71

When you write you firmware from the scratch you have to dive into SDK and found/derive the "channel" for yourself. It would be better if channel is provided in the event somehow, similar to what's done here: https://github.com/bigclownlabs/bcf-kit-wireless-motion-detector/blob/master/app/application.c#L58

What do you think about it?

**Comment by blavka** [comment]
But even there, it is initially assigned https://github.com/bigclownlabs/bcf-kit-wireless-motion-detector/blob/master/app/application.c#L113 .

But yes it is not entirely intuitive. It does not come to me, but correct the bc_radio.h dependence on the implementation of the sensors. But I will try to think of something.
